

GET {{url}}/products

###

GET {{url}}/product/2

###

POST {{url}}/product
Content-Type: application/json

{"name":"test asdf", "price": 22.22}

###

DELETE {{url}}/product/1

###

PUT {{url}}/product/2
Content-Type: application/json

{"name":"updated product", "price": 11.22}

###

PUT {{url}}/catsToPower

###

GET {{url}}/product/search/prod